### ISSUE TITLE
Start:1098 UPnP init () failed: -203

### ISSUE THREAD

**Issue by jcoz00** [GioF71/airconnect-docker#7]
Hello, upon starting the container it tries to start the UPnP service but I get the error: 

Start:1098 UPnP init in 192.168.1.2 () failed: -203

Any ideas on what may be causing this or how to fix it?

**Comment by GioF71** [comment]
Hello, can you post the full container logs? Thank you

**Comment by GioF71** [comment]
Looking at the issues in the upstream project, I found [this](https://github.com/philippe44/AirConnect/issues/183)
Can you provide details about your setup?
Thank you

**Comment by GioF71** [comment]
I don't think that you need to enable UPnP on the router.
This part looks wrong:

`- AIRCONNECT_MODE:upnp`

because of the ":" instead of "=" but anyway upnp is the default mode so this not the issue of course.

Which platform are you using? Also, are you running Docker Desktop or Docker Engine?

**Comment by GioF71** [comment]
Is the volume $DOCKERDIR/appdata/airconnect writable? Can you tried without volumes?

**Comment by jcoz00** [comment]
> Is the volume $DOCKERDIR/appdata/airconnect writable? Can you tried without volumes?

It should be? This is how I map all of my container's configs.



> I don't think that you need to enable UPnP on the router. This part looks wrong:
> 
> `- AIRCONNECT_MODE:upnp`
> 
> because of the ":" instead of "=" but anyway upnp is the default mode so this not the issue of course.
> 
> Which platform are you using? Also, are you running Docker Desktop or Docker Engine?

Whoops, fixed that. My server is running Ubuntu 24.04.1 LTS x86_64

**Comment by GioF71** [comment]
> > Is the volume $DOCKERDIR/appdata/airconnect writable? Can you tried without volumes?
> 
> It should be? This is how I map all of my container's configs.
> 

Yes, because the container run by default as uid:gid 1000:1000.
I did not add the option to leave it running as root yet, some kind of USER_MODE=no like I did on other container images of mine. I will do this as soon as possible. That would have avoided your permission issues.

> > I don't think that you need to enable UPnP on the router. This part looks wrong:
> > `- AIRCONNECT_MODE:upnp`
> > because of the ":" instead of "=" but anyway upnp is the default mode so this not the issue of course.
> > Which platform are you using? Also, are you running Docker Desktop or Docker Engine?
> 
> Whoops, fixed that. My server is running Ubuntu 24.04.1 LTS x86_64, Docker Compose.

Ok cool, the only issue is that docker compose did not support host networking until a very recent version (literally a few weeks ago), and host networking is a requirement for this application.

Please star the repo if you like the work!

**Comment by jcoz00** [comment]
Okay! I pulled the latest image but I am still getting the error..

Log output:

Container is running with uid=[0]
USER_MODE=[yes]
User mode enabled: [1]
Ensuring user with uid:[1000] gid:[1000] exists ...
Group with gid [1000] name [airc] already exists.
user with uid [1000] name [airc] already exists.
Using AirConnect [upnp] version [1.8.3]
Config directory [/config] is writable
Configuration file not found, creating reference configuration file ...
Command Line (config file creation): [/app/bin/airupnp-linux -i /config/config.xml]
[17:31:32.958] main:1386 Starting airupnp version: v1.8.3 (Feb  1 2024 @ 01:10:35)
[17:31:32.958] main:1393 no config file, using defaults
[17:31:32.961] Start:1094 Binding to iface 192.168.1.2:0 [enp0s31f6]
[17:31:32.961] Start:1098 UPnP init in 192.168.1.2 () failed: -203


Config:

services:
    airconnect:
        image: giof71/airconnect:latest
        container_name: airconnect
        network_mode: host
        restart: unless-stopped
        security_opt:
          - no-new-privileges:true
        environment:
          - TZ=$TZ
          - PGID=$PGID
          - PUID=$PUID
          - AIRCONNECT_MODE=upnp
          - LATENCY=1000:2000
          - CODEC=wav
          - USER_MODE=yes
          - USE_CONFIG_VOLUME=yes
        volumes:
          - $DOCKERDIR/appdata/airconnect:/config

**Comment by GioF71** [comment]
Hello, please try setting USER_MODE=no ...

**Comment by jcoz00** [comment]
Container is running with uid=[0]
USER_MODE=[no]
User mode enabled: [0]
Using AirConnect [upnp] version [1.8.3]
Config directory [/config] is writable
Configuration file not found, creating reference configuration file ...
Command Line (config file creation): [/app/bin/airupnp-linux -i /config/config.xml]
su: user airc does not exist or the user entry does not contain all the required fields
Configuration file created.
Setting CODEC to [wav] ...
Setting LATENCY to [1000:2000] ...
NETWORK_SELECT=
ENABLE_AUTO_NETWORK=[]
Automatically setting network ...
Automatically setting network [Done]
Command Line: [/app/bin/airupnp-linux -x /config/config.xml -Z -d all=debug -c wav -l 1000:2000 -b 192.168.1.2]
User mode disabled
[13:35:56.578] main:1386 Starting airupnp version: v1.8.3 (Feb  1 2024 @ 01:10:35)
[13:35:56.578] main:1393 no config file, using defaults
[13:35:56.585] Start:1094 Binding to iface 192.168.1.2:0 [enp0s31f6]
[13:35:56.585] Start:1098 UPnP init in 192.168.1.2 (192.168.1.2) failed: -203
[13:35:56.585] main:1425 Cannot start

**Comment by GioF71** [comment]
there's a bug here:

su: user airc does not exist or the user entry does not contain all the required fields

damn. I need to fix this!

**Comment by GioF71** [comment]
There is a new image building [now](https://github.com/GioF71/airconnect-docker/actions/runs/11372884256)...

**Comment by jcoz00** [comment]
Still no config file generated. Same error.

Container is running with uid=[0]
USER_MODE=[no]
User mode enabled: [0]
Using AirConnect [upnp] version [1.8.3]
Config directory [/config] is writable
Configuration file not found, creating reference configuration file ...
Command Line (config file creation): [/app/bin/airupnp-linux -i /config/config.xml]
User mode disabled
[15:07:04.046] main:1386 Starting airupnp version: v1.8.3 (Feb  1 2024 @ 01:10:35)
[15:07:04.046] main:1393 no config file, using defaults
[15:07:04.049] Start:1094 Binding to iface 192.168.1.2:0 [enp0s31f6]
[15:07:04.049] Start:1098 UPnP init in 192.168.1.2 () failed: -203

**Comment by jcoz00** [comment]
I will add that simply changing it to cast mode in the config fixes everything and works properly. Something with the UPnP mode is not right.

**Comment by GioF71** [comment]
ok this is where I find the application to be a little quirky. I also noticed that the file sometime is not saved. I believe that the best we can do is generate the file (I must provide information on how to do that, but essentially we must run 

/app/bin/airupnp-linux -i /config/config.xml

and then we need to mount the generated file directly. This is a little different from how SpotConnect works... SpotConnect works perfectly even starting from scratch and the file is always written. 
Unless I am missing something of course.

I ran the container with:

`docker run --rm -it -v ./config:/config --entrypoint /bin/bash giof71/airconnect`

and then ran:

`/app/bin/airupnp-linux -i /config/config.xml`

wait a while until it finished, but no file has been created. So weird!

**Comment by GioF71** [comment]
It worked using:

docker run --rm -it --network=host -v ./config:/config --entrypoint /bin/bash giof71/airconnect

then run this inside:

/app/bin/airupnp-linux -i /config/config.xml

Then I find the config.xml file. The app should then work. Make sure to mount the correct path!

**Comment by GioF71** [comment]
If this works for you as well, I will update the documentation.

**Comment by jcoz00** [comment]
I converted your docker run into a compose file and ran that to no avail. 

This is my output after running the command as well:

docker compose exec airconnect /app/bin/airupnp-linux -i /config/config.xml

no configuration file provided: not found

**Comment by jcoz00** [comment]
If I run with docker run:

user@User:~/docker$ sudo docker run --rm -it --network=host -v ./config:/config --entrypoint /bin/bash giof71/airconnect
root@User:/# /app/bin/airupnp-linux -i /config/config.xml
[20:45:56.516] main:1386 Starting airupnp version: v1.8.3 (Feb  1 2024 @ 01:10:35)
[20:45:56.516] main:1393 no config file, using defaults
[20:45:56.518] Start:1094 Binding to iface 192.168.1.2:0 [enp0s31f6]
[20:45:56.518] Start:1098 UPnP init in 192.168.1.2 () failed: -203

**Comment by GioF71** [comment]
Looks like the problem is with networking somehow. Could you try the application binaries out of docker?

**Comment by jcoz00** [comment]
Okay yes I did. Looks like it throws the same error. Weird.

./airupnp-linux-x86_64-static
[23:27:47.685] main:1386 Starting airupnp version: v1.8.3 (Feb  1 2024 @ 01:10:35)
[23:27:47.685] main:1393 no config file, using defaults
[23:27:47.691] Start:1094 Binding to iface 192.168.1.2:0 [enp0s31f6]
[23:27:47.691] Start:1098 UPnP init in 192.168.1.2 () failed: -203
[23:27:47.691] main:1425 Cannot start

**Comment by jcoz00** [comment]
Okay, my docker is also running Homebridge, which uses port 5353. The original docs for AirServer state that port 5353 is needed for mDNS. Could this be why?

**Comment by GioF71** [comment]
Hello, have a look [here](https://github.com/philippe44/AirConnect/issues/416).
The author commented about port 1900 and/or using the static version of the application.
Maybe verify if this port is already used? Looks like running in a system without docker solved the issue for the OP.
Do you have a spare device to use for a test?

**Comment by GioF71** [comment]
Hello jcoz00, is there any news?
One question I wanted to ask, is enp0s31f6 (and so address 192.168.1.2) where you want airconnect to run?

**Comment by jcoz00** [comment]
Okay I ran it on a Linux VM on my personal machine and it worked fine. And yes the 192.168.1.2 is the local IP of the server.

**Comment by GioF71** [comment]
Hello, thank  you.
But do you mean the container worked fine, or the binaries?

**Comment by jcoz00** [comment]
The VM was non-docker, so the binaries.

**Comment by jcoz00** [comment]
I will say that running the binaries on the docker server outside of a containerized environment produced the same error. Must be an issue with the machine/networking setup itself?

**Comment by GioF71** [comment]
> I will say that running the binaries on the docker server outside of a containerized environment produced the same error. Must be an issue with the machine/networking setup itself?

Yes, I suppose. Maybe you can open an issue on the AirConnect repository [here](https://github.com/philippe44/AirConnect).
If you can solve this, and some changes are needed in the container image, I will try to implement those changes.
Also I still have to update the documentation about how to generate a configuration file. I guest next week I might have a few moments for that.

**Comment by jcoz00** [comment]
Sounds good! Thanks for your help in narrowing that down.

**Comment by jcoz00** [comment]
Found out it was Plex port 1900/udp interferring with it!

**Comment by GioF71** [comment]
Excellent! Thank you!
